/* alphasvr_client.h

 Generated by phxrpc_pb2client from alpha_svr.proto

*/

#pragma once

#include "alpha_svr.pb.h"
#include "phxrpc/rpc.h"


class AlphaSvrClient {
  public:
    static bool Init(const char *config_file);

    static const char *GetPackageName();

    AlphaSvrClient();
    virtual ~AlphaSvrClient();

    int PHXEcho(const google::protobuf::StringValue &req, google::protobuf::StringValue *resp);
    int PHXBatchEcho(const google::protobuf::StringValue &req, google::protobuf::StringValue *resp);
    int AddTwoDigits(const alphasvr::AddTwoDigitsReq &req, alphasvr::AddTwoDigitsResp *resp);
    int AddSomeDigits(const alphasvr::AddSomeDigitsReq &req, alphasvr::AddSomeDigitsResp *resp);
};

