/* alphasvr_service_impl.h

 Generated by phxrpc_pb2service from alpha_svr.proto

*/

#pragma once

#include "alpha_svr.pb.h"
#include "phxrpc_alphasvr_service.h"


class AlphaSvrServerConfig;

typedef struct tagServiceArgs {
    AlphaSvrServerConfig *config;
    // you can add other arguments here and initiate in main().
} ServiceArgs_t;

class AlphaSvrServiceImpl : public AlphaSvrService {
  public:
    AlphaSvrServiceImpl(ServiceArgs_t &app_args);
    virtual ~AlphaSvrServiceImpl() override;

    virtual int PHXEcho(const google::protobuf::StringValue &req, google::protobuf::StringValue *resp) override;
    virtual int AddTwoDigits(const alphasvr::AddTwoDigitsReq &req, alphasvr::AddTwoDigitsResp *resp) override;
    virtual int AddSomeDigits(const alphasvr::AddSomeDigitsReq &req, alphasvr::AddSomeDigitsResp *resp) override;

  private:
    ServiceArgs_t &args_;
};

