/* alphasvr_tool_impl.h

 Generated by phxrpc_pb2tool from alpha_svr.proto

*/

#pragma once

#include "phxrpc_alphasvr_tool.h"


namespace phxrpc {


class OptMap;


}


class AlphaSvrToolImpl : public AlphaSvrTool {
  public:
    AlphaSvrToolImpl();
    virtual ~AlphaSvrToolImpl() override;

    virtual int PHXEcho(phxrpc::OptMap &opt_map) override;
    virtual int AddTwoDigits(phxrpc::OptMap &opt_map) override;
    virtual int AddSomeDigits(phxrpc::OptMap &opt_map) override;
};

