/* alphasvr_client.cpp

 Generated by phxrpc_pb2client from alpha_svr.proto

*/

#include "alphasvr_client.h"

#include <cstdlib>
#include <memory>
#include <mutex>

#include "phxrpc/http.h"
#include "phxrpc/rpc.h"

#include "phxrpc_alphasvr_stub.h"


using namespace std;


static phxrpc::ClientConfig global_alphasvrclient_config_;
static phxrpc::ClientMonitorPtr global_alphasvrclient_monitor_;


bool AlphaSvrClient::Init(const char *config_file) {
    return global_alphasvrclient_config_.Read(config_file);
}

const char *AlphaSvrClient::GetPackageName() {
    const char *ret = global_alphasvrclient_config_.GetPackageName();
    if (strlen(ret) == 0) {
        ret = "alphasvr";
    }
    return ret;
}

AlphaSvrClient::AlphaSvrClient() {
    static mutex monitor_mutex;
    if (!global_alphasvrclient_monitor_.get()) {
        monitor_mutex.lock();
        if (!global_alphasvrclient_monitor_.get()) {
            global_alphasvrclient_monitor_ = phxrpc::MonitorFactory::GetFactory()->
                    CreateClientMonitor(GetPackageName());
        }
        global_alphasvrclient_config_.SetClientMonitor(global_alphasvrclient_monitor_);
        monitor_mutex.unlock();
    }
}

AlphaSvrClient::~AlphaSvrClient() {
}

int AlphaSvrClient::PHXEcho(const google::protobuf::StringValue &req, google::protobuf::StringValue *resp)
{
    const phxrpc::Endpoint_t *ep{global_alphasvrclient_config_.GetRandom()};

    if (ep) {
        phxrpc::BlockTcpStream socket;
        bool open_ret{phxrpc::PhxrpcTcpUtils::Open(&socket, ep->ip, ep->port,
                global_alphasvrclient_config_.GetConnectTimeoutMS(), nullptr, 0,
                *(global_alphasvrclient_monitor_.get()))};
        if (open_ret) {
            socket.SetTimeout(global_alphasvrclient_config_.GetSocketTimeoutMS());
            phxrpc::HttpMessageHandlerFactory http_msg_factory;
            AlphaSvrStub stub(socket, *(global_alphasvrclient_monitor_.get()), http_msg_factory);
            return stub.PHXEcho(req, resp);
        }

    }

    return -1;
}

int AlphaSvrClient::PHXBatchEcho(const google::protobuf::StringValue &req, google::protobuf::StringValue *resp)
{
    int ret{-1};
    size_t echo_server_count{2};
    uthread_begin;
    for (size_t i{0}; echo_server_count > i; ++i) {
        uthread_t [=, &uthread_s, &ret](void *) {
            const phxrpc::Endpoint_t *ep = global_alphasvrclient_config_.GetByIndex(i);
            if (ep != nullptr) {
                phxrpc::UThreadTcpStream socket;
                if (phxrpc::PhxrpcTcpUtils::Open(&uthread_s, &socket, ep->ip, ep->port,
                    global_alphasvrclient_config_.GetConnectTimeoutMS(), *(global_alphasvrclient_monitor_.get()))) {
                    socket.SetTimeout(global_alphasvrclient_config_.GetSocketTimeoutMS());
                    phxrpc::HttpMessageHandlerFactory http_msg_factory;
                    AlphaSvrStub stub(socket, *(global_alphasvrclient_monitor_.get()), http_msg_factory);
                    int this_ret{stub.PHXEcho(req, resp)};
                    if (this_ret == 0) {
                        ret = this_ret;
                        uthread_s.Close();
                    }
                }
            }
        };
    }
    uthread_end;
    return ret;
}

int AlphaSvrClient::AddTwoDigits(const alphasvr::AddTwoDigitsReq &req, alphasvr::AddTwoDigitsResp *resp)
{
    const phxrpc::Endpoint_t *ep{global_alphasvrclient_config_.GetRandom()};

    if (ep) {
        phxrpc::BlockTcpStream socket;
        bool open_ret{phxrpc::PhxrpcTcpUtils::Open(&socket, ep->ip, ep->port,
                global_alphasvrclient_config_.GetConnectTimeoutMS(), nullptr, 0,
                *(global_alphasvrclient_monitor_.get()))};
        if (open_ret) {
            socket.SetTimeout(global_alphasvrclient_config_.GetSocketTimeoutMS());
            phxrpc::HttpMessageHandlerFactory http_msg_factory;
            AlphaSvrStub stub(socket, *(global_alphasvrclient_monitor_.get()), http_msg_factory);
            return stub.AddTwoDigits(req, resp);
        }

    }

    return -1;
}

int AlphaSvrClient::AddSomeDigits(const alphasvr::AddSomeDigitsReq &req, alphasvr::AddSomeDigitsResp *resp)
{
    const phxrpc::Endpoint_t *ep{global_alphasvrclient_config_.GetRandom()};

    if (ep) {
        phxrpc::BlockTcpStream socket;
        bool open_ret{phxrpc::PhxrpcTcpUtils::Open(&socket, ep->ip, ep->port,
                global_alphasvrclient_config_.GetConnectTimeoutMS(), nullptr, 0,
                *(global_alphasvrclient_monitor_.get()))};
        if (open_ret) {
            socket.SetTimeout(global_alphasvrclient_config_.GetSocketTimeoutMS());
            phxrpc::HttpMessageHandlerFactory http_msg_factory;
            AlphaSvrStub stub(socket, *(global_alphasvrclient_monitor_.get()), http_msg_factory);
            return stub.AddSomeDigits(req, resp);
        }

    }

    return -1;
}

