/* alphasvr_service_impl.cpp

 Generated by phxrpc_pb2service from alpha_svr.proto

*/

#include "alphasvr_service_impl.h"

#include "phxrpc/file.h"

#include "alphasvr_server_config.h"
#include "alpha_svr.pb.h"


using namespace std;


AlphaSvrServiceImpl::AlphaSvrServiceImpl(ServiceArgs_t &app_args) : args_(app_args) {
}

AlphaSvrServiceImpl::~AlphaSvrServiceImpl() {
}

int AlphaSvrServiceImpl::PHXEcho(const google::protobuf::StringValue &req, google::protobuf::StringValue *resp) {
    resp->set_value(req.value());
    return 0;
}

int AlphaSvrServiceImpl::AddTwoDigits(const alphasvr::AddTwoDigitsReq &req, alphasvr::AddTwoDigitsResp *resp) {
    int num1 = req.lhs();
    int num2 = req.rhs();
    int ans = num1 +num2;
    resp->set_sum(ans);
    return 0;
}

int AlphaSvrServiceImpl::AddSomeDigits(const alphasvr::AddSomeDigitsReq &req, alphasvr::AddSomeDigitsResp *resp) {
    return -1;
}

