/* alphasvr_server_config.cpp

 Generated by phxrpc_pb2server from alpha_svr.proto

*/

#include "alphasvr_server_config.h"

#include "alpha_svr.pb.h"


AlphaSvrServerConfig::AlphaSvrServerConfig() {
}

AlphaSvrServerConfig::~AlphaSvrServerConfig() {
}

bool AlphaSvrServerConfig::Read(const char *config_file) {
    bool ret{ep_server_config_.Read(config_file)};

    if (0 == strlen(ep_server_config_.GetPackageName())) {
        ep_server_config_.SetPackageName(
                alphasvr::AddTwoDigitsReq::default_instance().GetDescriptor()->file()->package().c_str());
    }

    return ret;
}

phxrpc::HshaServerConfig &AlphaSvrServerConfig::GetHshaServerConfig() {
    return ep_server_config_;
}

