/* phxrpc_alphasvr_dispatcher.h

 Generated by phxrpc_pb2service from alpha_svr.proto

 Please DO NOT edit unless you know exactly what you are doing.

*/

#include "phxrpc_alphasvr_dispatcher.h"

#include <errno.h>

#include "phxrpc/http.h"
#include "phxrpc/file.h"

#include "alpha_svr.pb.h"
#include "phxrpc_alphasvr_service.h"


AlphaSvrDispatcher::AlphaSvrDispatcher(AlphaSvrService &service, phxrpc::DispatcherArgs_t *dispatcher_args)
        : service_(service), dispatcher_args_(dispatcher_args) {
}

AlphaSvrDispatcher::~AlphaSvrDispatcher() {
}

const phxrpc::BaseDispatcher<AlphaSvrDispatcher>::URIFuncMap &AlphaSvrDispatcher::GetURIFuncMap() {
    static phxrpc::BaseDispatcher<AlphaSvrDispatcher>::URIFuncMap uri_func_map = {
        {"/alphasvr/PHXEcho", &AlphaSvrDispatcher::PHXEcho},
        {"/alphasvr/AddTwoDigits", &AlphaSvrDispatcher::AddTwoDigits},
        {"/alphasvr/AddSomeDigits", &AlphaSvrDispatcher::AddSomeDigits}};
    return uri_func_map;
}

int AlphaSvrDispatcher::PHXEcho(const phxrpc::BaseRequest &req, phxrpc::BaseResponse *const resp) {
    dispatcher_args_->server_monitor->SvrCall(-1, "PHXEcho", 1);

    int ret{-1};

    google::protobuf::StringValue req_pb;
    google::protobuf::StringValue resp_pb;

    // unpack request
    {
        ret = req.ToPb(&req_pb);
        if (0 != ret) {
            phxrpc::log(LOG_ERR, "ToPb err %d", ret);

            return -EINVAL;
        }
    }

    // logic process
    {
        if (0 == ret) {
            ret = service_.PHXEcho(req_pb, &resp_pb);
        }
    }

    // pack response
    {
        if (0 != resp->FromPb(resp_pb)) {
            phxrpc::log(LOG_ERR, "FromPb err %d", ret);

            return -ENOMEM;
        }
    }

    phxrpc::log(LOG_DEBUG, "RETN: PHXEcho = %d", ret);

    return ret;
}

int AlphaSvrDispatcher::AddTwoDigits(const phxrpc::BaseRequest &req, phxrpc::BaseResponse *const resp) {
    dispatcher_args_->server_monitor->SvrCall(1, "AddTwoDigits", 1);

    int ret{-1};

    alphasvr::AddTwoDigitsReq req_pb;
    alphasvr::AddTwoDigitsResp resp_pb;

    // unpack request
    {
        ret = req.ToPb(&req_pb);
        if (0 != ret) {
            phxrpc::log(LOG_ERR, "ToPb err %d", ret);

            return -EINVAL;
        }
    }

    // logic process
    {
        if (0 == ret) {
            ret = service_.AddTwoDigits(req_pb, &resp_pb);
        }
    }

    // pack response
    {
        if (0 != resp->FromPb(resp_pb)) {
            phxrpc::log(LOG_ERR, "FromPb err %d", ret);

            return -ENOMEM;
        }
    }

    phxrpc::log(LOG_DEBUG, "RETN: AddTwoDigits = %d", ret);

    return ret;
}

int AlphaSvrDispatcher::AddSomeDigits(const phxrpc::BaseRequest &req, phxrpc::BaseResponse *const resp) {
    dispatcher_args_->server_monitor->SvrCall(2, "AddSomeDigits", 1);

    int ret{-1};

    alphasvr::AddSomeDigitsReq req_pb;
    alphasvr::AddSomeDigitsResp resp_pb;

    // unpack request
    {
        ret = req.ToPb(&req_pb);
        if (0 != ret) {
            phxrpc::log(LOG_ERR, "ToPb err %d", ret);

            return -EINVAL;
        }
    }

    // logic process
    {
        if (0 == ret) {
            ret = service_.AddSomeDigits(req_pb, &resp_pb);
        }
    }

    // pack response
    {
        if (0 != resp->FromPb(resp_pb)) {
            phxrpc::log(LOG_ERR, "FromPb err %d", ret);

            return -ENOMEM;
        }
    }

    phxrpc::log(LOG_DEBUG, "RETN: AddSomeDigits = %d", ret);

    return ret;
}

