/* phxrpc_alphasvr_service.h

 Generated by phxrpc_pb2service from alpha_svr.proto

 Please DO NOT edit unless you know exactly what you are doing.

*/

#pragma once

#include "alpha_svr.pb.h"


class AlphaSvrService {
  public:
    AlphaSvrService();
    virtual ~AlphaSvrService();

    virtual int PHXEcho(const google::protobuf::StringValue &req, google::protobuf::StringValue *resp);
    virtual int AddTwoDigits(const alphasvr::AddTwoDigitsReq &req, alphasvr::AddTwoDigitsResp *resp);
    virtual int AddSomeDigits(const alphasvr::AddSomeDigitsReq &req, alphasvr::AddSomeDigitsResp *resp);
};

