/* phxrpc_alphasvr_service.cpp

 Generated by phxrpc_pb2service from alpha_svr.proto

 Please DO NOT edit unless you know exactly what you are doing.

*/

#include "phxrpc_alphasvr_service.h"

#include "alpha_svr.pb.h"
#include "phxrpc/file.h"


AlphaSvrService::AlphaSvrService() {
}

AlphaSvrService::~AlphaSvrService() {
}

int AlphaSvrService::PHXEcho(const google::protobuf::StringValue &/* req */, google::protobuf::StringValue */* resp */) {
    phxrpc::log(LOG_ERR, "ERROR: PHXEcho unimplemented");
    return -1;
}

int AlphaSvrService::AddTwoDigits(const alphasvr::AddTwoDigitsReq &/* req */, alphasvr::AddTwoDigitsResp */* resp */) {
    phxrpc::log(LOG_ERR, "ERROR: AddTwoDigits unimplemented");
    return -1;
}

int AlphaSvrService::AddSomeDigits(const alphasvr::AddSomeDigitsReq &/* req */, alphasvr::AddSomeDigitsResp */* resp */) {
    phxrpc::log(LOG_ERR, "ERROR: AddSomeDigits unimplemented");
    return -1;
}

