/* phxrpc_alphasvr_tool.cpp

 Generated by phxrpc_pb2tool from alpha_svr.proto

 Please DO NOT edit unless you know exactly what you are doing.

*/

#include "phxrpc_alphasvr_tool.h"

#include "phxrpc/file.h"

#include "alphasvr_client.h"


using namespace phxrpc;


AlphaSvrTool::AlphaSvrTool() {
}

AlphaSvrTool::~AlphaSvrTool() {
}

int AlphaSvrTool::PHXEcho(phxrpc::OptMap &/* opt_map */) {
    printf("\n    *** PHXEcho unimplement ***\n");

    return -1;
}

int AlphaSvrTool::AddTwoDigits(phxrpc::OptMap &/* opt_map */) {
    printf("\n    *** AddTwoDigits unimplement ***\n");

    return -1;
}

int AlphaSvrTool::AddSomeDigits(phxrpc::OptMap &/* opt_map */) {
    printf("\n    *** AddSomeDigits unimplement ***\n");

    return -1;
}

