/* phxrpc_alphasvr_stub.cpp

 Generated by phxrpc_pb2client from alpha_svr.proto

 Please DO NOT edit unless you know exactly what you are doing.

*/

#include "phxrpc_alphasvr_stub.h"

#include "phxrpc/http.h"
#include "phxrpc/network.h"
#include "phxrpc/rpc.h"


AlphaSvrStub::AlphaSvrStub(phxrpc::BaseTcpStream &socket, phxrpc::ClientMonitor &client_monitor,
        phxrpc::BaseMessageHandlerFactory &msg_handler_factory)
        : socket_(socket), client_monitor_(client_monitor),
          msg_handler_factory_(msg_handler_factory) {
}

AlphaSvrStub::~AlphaSvrStub() {
}

void AlphaSvrStub::set_keep_alive(const bool keep_alive) {
    keep_alive_ = keep_alive;
}

int AlphaSvrStub::PHXEcho(const google::protobuf::StringValue &req, google::protobuf::StringValue *resp) {
    phxrpc::Caller caller(socket_, client_monitor_, msg_handler_factory_);
    caller.set_uri("/alphasvr/PHXEcho", -1);
    caller.set_keep_alive(keep_alive_);
    return caller.Call(req, resp);
}

int AlphaSvrStub::AddTwoDigits(const alphasvr::AddTwoDigitsReq &req, alphasvr::AddTwoDigitsResp *resp) {
    phxrpc::Caller caller(socket_, client_monitor_, msg_handler_factory_);
    caller.set_uri("/alphasvr/AddTwoDigits", 1);
    caller.set_keep_alive(keep_alive_);
    return caller.Call(req, resp);
}

int AlphaSvrStub::AddSomeDigits(const alphasvr::AddSomeDigitsReq &req, alphasvr::AddSomeDigitsResp *resp) {
    phxrpc::Caller caller(socket_, client_monitor_, msg_handler_factory_);
    caller.set_uri("/alphasvr/AddSomeDigits", 2);
    caller.set_keep_alive(keep_alive_);
    return caller.Call(req, resp);
}

