/* phxrpc_alphasvr_tool.h

 Generated by phxrpc_pb2tool from alpha_svr.proto

 Please DO NOT edit unless you know exactly what you are doing.

*/

#pragma once


namespace phxrpc {


class OptMap;


}


class AlphaSvrTool {
  public:
    AlphaSvrTool();
    virtual ~AlphaSvrTool();

    virtual int PHXEcho(phxrpc::OptMap &bigmap);
    virtual int AddTwoDigits(phxrpc::OptMap &bigmap);
    virtual int AddSomeDigits(phxrpc::OptMap &bigmap);

    typedef int (AlphaSvrTool::*ToolFunc_t)(phxrpc::OptMap &);

    typedef struct tagName2Func {
        const char *name;
        AlphaSvrTool::ToolFunc_t func;
        const char *opt_string;
        const char *usage;
    } Name2Func_t;

    static Name2Func_t *GetName2Func() {
        static Name2Func_t name2func[]{
            {"PHXEcho", &AlphaSvrTool::PHXEcho, "c:f:vs:",
                    "-s <string>"},
            {"AddTwoDigits", &AlphaSvrTool::AddTwoDigits, "c:f:vl:r:",
                    "-l digit1 -u digit2"},
            {"AddSomeDigits", &AlphaSvrTool::AddSomeDigits, "c:f:vv:",
                    "-v digit_split_by_&"},
            {nullptr, nullptr}
        };

        return name2func;
    };
};

