/* search_tool_impl.h

 Generated by phxrpc_pb2tool from search.proto

*/

#pragma once

#include "phxrpc_search_tool.h"


namespace phxrpc {


class OptMap;


}


class SearchToolImpl : public SearchTool {
  public:
    SearchToolImpl();
    virtual ~SearchToolImpl() override;

    virtual int PHXEcho(phxrpc::OptMap &opt_map) override;
    virtual int Search(phxrpc::OptMap &opt_map) override;
    virtual int Notify(phxrpc::OptMap &opt_map) override;
};

