/* search_server_config.h

 Generated by phxrpc_pb2server from search.proto

*/

#pragma once

#include "phxrpc/rpc.h"


class SearchServerConfig {
  public:
    SearchServerConfig();

    virtual ~SearchServerConfig();

    bool Read(const char *config_file);

    phxrpc::HshaServerConfig &GetHshaServerConfig();

  private:
    phxrpc::HshaServerConfig ep_server_config_;
};

