/* search_server_config.cpp

 Generated by phxrpc_pb2server from search.proto

*/

#include "search_server_config.h"

#include "search.pb.h"


SearchServerConfig::SearchServerConfig() {
}

SearchServerConfig::~SearchServerConfig() {
}

bool SearchServerConfig::Read(const char *config_file) {
    bool ret{ep_server_config_.Read(config_file)};

    if (0 == strlen(ep_server_config_.GetPackageName())) {
        ep_server_config_.SetPackageName(
                search::SearchRequest::default_instance().GetDescriptor()->file()->package().c_str());
    }

    return ret;
}

phxrpc::HshaServerConfig &SearchServerConfig::GetHshaServerConfig() {
    return ep_server_config_;
}

