/* search_client.h

 Generated by phxrpc_pb2client from search.proto

*/

#pragma once

#include "search.pb.h"
#include "phxrpc/rpc.h"


class SearchClient {
  public:
    static bool Init(const char *config_file);

    static const char *GetPackageName();

    SearchClient();
    virtual ~SearchClient();

    int PHXEcho(const google::protobuf::StringValue &req, google::protobuf::StringValue *resp);
    int PHXBatchEcho(const google::protobuf::StringValue &req, google::protobuf::StringValue *resp);
    int Search(const search::SearchRequest &req, search::SearchResult *resp);
    int Notify(const google::protobuf::StringValue &req, google::protobuf::Empty *resp);
};

